[READY] Reduce hex size
PurdueElectricRacing/firmware pull request #129
Opened 2024-09-02 13:05 UTC by mcgalliard

6 months ago no fill was added to post build hex copying. This caused some hex inflation - up to 1GB....
This needed to be removed

2024-09-02 15:37 UTC, zyonse commented
Why was gap fill originally enabled?

2024-09-02 15:55 UTC, mcgalliard commented
> Why was gap fill originally enabled?
See [https://github.com/PurdueElectricRacing/firmware/commit/1248be27d0e4654c988086544c2231785b8e73e2](url)
"Main module output had multiple segments (only a few bytes away). The bootloader doesn't support jumps in address, so we will just send some zeros to fill the gap"

We will need to add bootloader support for jumps in address

2024-09-02 16:01 UTC, zyonse submitted a review, later dismissed

2024-09-02 17:17 UTC, AdityaAsGithub requested changes
Underlying issue necessitating gap fill should be fixed before this gets merged into master.

2024-09-03 20:30 UTC, ColexDev commented
The link you sent in response to Gavin leads to a 404 for me. I would also like to see the original reasoning behind why we added the gap-fill flag as well.

> The bootloader doesn't support jumps in address

What? Why is this? The bootloader is not able to jump and has to run sequentially?

2024-09-03 23:00 UTC, zyonse commented
@ColexDev this is the commit he linked: https://github.com/PurdueElectricRacing/firmware/commit/1248be27d0e4654c988086544c2231785b8e73e2

2024-09-07 06:14 UTC, AdityaAsGithub approved these changes

2024-09-08 19:17 UTC, ColexDev submitted a review, later dismissed

2024-09-08 20:44 UTC, irvingywang submitted a review, later dismissed

2024-09-11 07:14 UTC, AdityaAsGithub requested changes
This MR should not merge, for the same reason I mentioned earlier

2024-09-12 04:40 UTC, AdityaAsGithub submitted a review, later dismissed

2024-09-12 04:43 UTC, LukeOxley submitted a review, later dismissed
Test :•)

2024-12-16 05:38 UTC, closed without merging