[DRAFT] Setup Documentation Update
PurdueElectricRacing/firmware pull request #135
Opened 2024-09-10 02:33 UTC by irvingywang

- Requires testing.
- Open to revisions, this is a draft.

2024-09-10 13:32 UTC, mcgalliard submitted a review, later dismissed

2024-09-11 01:28 UTC, irvingywang commented
MacOS install tested and working

2024-09-11 02:29 UTC, ColexDev submitted a review, later dismissed

2024-09-13 00:27 UTC, zyonse requested changes

2024-09-13 00:27 UTC, zyonse commented on setup.md
> +    - Windows: `mingw-w64-x86_64-ninja`.
Some commands are missing "pacman -S"

2024-09-13 02:33 UTC, irvingywang commented on setup.md
> +    - Windows: `mingw-w64-x86_64-ninja`.
fixed, good catch

2024-09-15 18:27 UTC, zyonse approved these changes
Should be ready now

2024-09-15 19:53 UTC, irvingywang commented
@mcgalliard 1 approval needed to merge

2024-09-15 21:17 UTC, ColexDev approved these changes

2024-09-17 21:39 UTC, AdityaAsGithub approved these changes

2024-09-17 22:00 UTC, merged