pdu can
PurdueElectricRacing/firmware pull request #97
Opened 2024-02-24 20:40 UTC by nverapae

2024-02-24 21:26 UTC, AdityaAsGithub requested changes
Add more comments

2024-02-29 13:35 UTC, LukeOxley requested changes

2024-02-29 13:35 UTC, LukeOxley commented on source/pdu/cooling/cooling.c
> +void update_cooling_periodic() {
why have periodic function if you are using callback

2024-03-02 15:53 UTC, LukeOxley approved these changes

2024-03-14 17:19 UTC, AdityaAsGithub approved these changes

2024-03-15 02:23 UTC, merged